version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - groww
  - isin
  - mahato
  - mulyam
  - noto
  - piyush
  - papaparse
  - supabase
  - unpdf
  - xirr
import: []
